//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USB) DeepCopyInto(out *USB) {
	*out = *in
	if in.USBHostDevices != nil {
		in, out := &in.USBHostDevices, &out.USBHostDevices
		*out = make([]USBHostDevices, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USB.
func (in *USB) DeepCopy() *USB {
	if in == nil {
		return nil
	}
	out := new(USB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDevicesConfig) DeepCopyInto(out *USBDevicesConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDevicesConfig.
func (in *USBDevicesConfig) DeepCopy() *USBDevicesConfig {
	if in == nil {
		return nil
	}
	out := new(USBDevicesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *USBDevicesConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDevicesConfigList) DeepCopyInto(out *USBDevicesConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]USBDevicesConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDevicesConfigList.
func (in *USBDevicesConfigList) DeepCopy() *USBDevicesConfigList {
	if in == nil {
		return nil
	}
	out := new(USBDevicesConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *USBDevicesConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDevicesConfigSpec) DeepCopyInto(out *USBDevicesConfigSpec) {
	*out = *in
	if in.USB != nil {
		in, out := &in.USB, &out.USB
		*out = make([]USB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDevicesConfigSpec.
func (in *USBDevicesConfigSpec) DeepCopy() *USBDevicesConfigSpec {
	if in == nil {
		return nil
	}
	out := new(USBDevicesConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDevicesConfigStatus) DeepCopyInto(out *USBDevicesConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDevicesConfigStatus.
func (in *USBDevicesConfigStatus) DeepCopy() *USBDevicesConfigStatus {
	if in == nil {
		return nil
	}
	out := new(USBDevicesConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBHostDevices) DeepCopyInto(out *USBHostDevices) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBHostDevices.
func (in *USBHostDevices) DeepCopy() *USBHostDevices {
	if in == nil {
		return nil
	}
	out := new(USBHostDevices)
	in.DeepCopyInto(out)
	return out
}
