// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (USBDevicesConfig) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "USBDevicesConfig represents a subset of USB devices that we want to expose\nto virtual machines.\n\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+genclient",
	}
}

func (USBDevicesConfigSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"usb": "+listType=atomic",
	}
}

func (USB) SwaggerDoc() map[string]string {
	return map[string]string{
		"":               "USB defines a group of USB devices based on its selectors and combine them under a single\nresource name, to be allocated to the VM",
		"resourceName":   "Identifies the list of USB host devices.\ne.g: kubevirt.io/storage, kubevirt.io/bootable-usb, etc",
		"usbHostDevices": "+listType=atomic",
	}
}

func (USBHostDevices) SwaggerDoc() map[string]string {
	return map[string]string{
		"selectByVendorProduct": "The vendor:product of the devices we want to select.\ne.g: \"0951:1666\"",
	}
}

func (USBDevicesConfigStatus) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (USBDevicesConfigList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}
